rithis_store_get_cart:
    pattern: /cart
    defaults: { _controller: RithisStoreBundle:Cart:getCart }
    requirements:
        _method: GET

rithis_store_post_cart:
    pattern: /cart
    defaults: { _controller: RithisStoreBundle:Cart:postCart }
    requirements:
        _method: POST

rithis_store_patch_cart:
    pattern: /cart
    defaults: { _controller: RithisStoreBundle:Cart:patchCart }
    requirements:
        _method: PATCH

rithis_store_post_cart_products:
    pattern: /cart/products
    defaults: { _controller: RithisStoreBundle:Cart:postCartProducts }
    requirements:
        _method: POST

rithis_store_get_category:
    pattern: /{categorySlug}
    defaults: { _controller: RithisStoreBundle:Categories:getCategory }
    requirements:
        _method: GET

rithis_store_get_brand:
    pattern: /{categorySlug}/{brandSlug}
    defaults: { _controller: RithisStoreBundle:Brands:getBrand }
    requirements:
        _method: GET

rithis_store_get_product:
    pattern: /{categorySlug}/{brandSlug}/{productSlug}
    defaults: { _controller: RithisStoreBundle:Products:getProduct }
    requirements:
        _method: GET
