parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

    database_driver: pdo_mysql
    database_host: localhost
    database_port: ~
    database_name: tunisiansun
    database_user: root
    database_password: ~
    database_path: ~

    asset_url_pattern: http://tunisiansun.com/uploads/store/%s
