admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_rithis_session:
    resource: "@RithisSessionBundle/Resources/config/routing.yml"

_rithis_store:
    resource: "@RithisStoreBundle/Resources/config/routing.yml"
